- name: install hyprland
  become: true
  package:
    update_cache: yes
    name:
      - hyprland
      - waybar
      - rofi
      - wofi
      - dunst
      - dolphin
      - xdg-desktop-portal-hyprland
      - qt5-wayland
      - qt6-wayland
      - hyprpaper
      - chromium
      - ttf-font-awesome
      - wayland

