- name: install hyprland
  become: true
  package:
    update_cache: yes
    name:
      - chromium
      - dolphin
      - dunst
      - gtk3
      - hyprland
      - hyprpaper
      - qt5-wayland
      - qt6-wayland
      - rofi
      - sway
      - ttf-font-awesome
      - waybar
      - wayland
      - wofi
      - xdg-desktop-portal-hyprland

- copy:
    src: "{{ role_path }}/files/hyprland.conf"
    dest: "/home/jp/.config/hypr/hyprland.conf"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/jp/.config/waybar/hypr/
    state: directory
    mode: '0755'

- copy:
    src: "{{ role_path }}/files/waybar"
    dest: "/home/jp/.config/waybar/hypr/config"