- name: install hyprland
  become: true
  package:
    update_cache: yes
    name:
      - chromium
      - dolphin
      - dunst
      - hyprland
      - hyprlang
      - hyprpaper
      - qt5-wayland
      - qt6-wayland
      - rofi
      - ttf-font-awesome
      - waybar
      - wayland
      - wofi
      - xdg-desktop-portal-hyprland
    state: absent

