- name: install hyprland
  become: true
  package:
    update_cache: yes
    name:
      - chromium
      - dolphin
      - dunst
      - hyprland
      - hyprpaper
      - qt5-wayland
      - qt6-wayland
      - rofi
      - ttf-font-awesome
      - waybar
      - wayland
      - wofi
      - xdg-desktop-portal-hyprland

- copy:
    become_user: jp
    src: "{{ role_path }}/files/hyprland.conf"
    dest: "/home/jp/.config/hyprland.conf"