- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - base-devel
    - gimp
    - git
    - lsd
    - source-highlight
    - thefuck
    - tmux
    - tree
    - vim
    - vlc
    - wezterm
   state: present

- name: Install archive utils
  pacman:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
      - aria2
      - curl
      - wget
    state: present

