# - import_tasks: repos.yml

- name: install tools
  become: true
  dnf:
    name:
      # LinuxBrew Dependencies
      - "@Development Tools"
      - "@Multimedia"
      - procps-ng
      - curl
      - file
      - libxcrypt-compat

      # gui
      - alacritty
      - brave-browser-beta
      - dconf-editor
      - discord
      # - element
      - gnome-tweaks
      - kitty
      - foot
      - waybar
      - sway
      - wdisplays
      - nwg-launchers
      - nwg-panel
      - slurp
      - grim
      - wev
      - swaylock-effects
      - imv
      - blueman

      # Wayland Development
      - wayland-devel
      - libxkbcommon-devel

      # Gaming
      - lutris
      - steam
      - wine
      - mangohud

      # utils
      - clipman
      - pulseaudio-utils
      - playerctl
      - brightnessctl
      - wob
      - fuzzel
      - wofi
      - bemenu
      - rofi-wayland
      - rofimoji
      - lm_sensors
      - gammastep-indicator

      # cli
      - aria2
      - aspell
      - bat
      - bandwhich
      - bottom
      - ctop
      - curl
      - gh
      - git-delta
      - exa
      - fd-find
      - direnv
      - fzf
      - fzy
      - git
      - git-lfs
      # - glow
      - gnupg
      - gnuplot
      - htop
      - httpie
      - hub
      - hyperfine
      - jq
      # - languagetool
      - lazydocker
      - lazygit
      - neovim
      - nnn
      - nodejs
      - ncdu
      - osmium-tool
      - pass
      - procs
      - qemu
      - ranger
      - ripgrep
      - ShellCheck
      - shfmt
      - tealdeer
      - tmux
      # - tmuxinator
      - tokei
      - weechat
      - wget
      - wezterm
      - zoxide

- name: install brew tools
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    name:
      # cli
      - as-tree
      - broot
      - duf
      - dust
      - grc
      - markdownlint-cli
      - mdcat
      - pfetch
      - selene
      - stylua
      - starship
# - import_tasks: repos.yml

- name: install tools
  become: true
  dnf:
    name:
      # LinuxBrew Dependencies
      - "@Development Tools"
      - "@Multimedia"
      - procps-ng
      - curl
      - file
      - libxcrypt-compat

      # gui
      - alacritty
      - brave-browser-beta
      - dconf-editor
      - discord
      # - element
      - gnome-tweaks
      - kitty
      - foot
      - waybar
      - sway
      - wdisplays
      - nwg-launchers
      - nwg-panel
      - slurp
      - grim
      - wev
      - swaylock-effects
      - imv
      - blueman

      # Wayland Development
      - wayland-devel
      - libxkbcommon-devel

      # Gaming
      - lutris
      - steam
      - wine
      - mangohud

      # utils
      - clipman
      - pulseaudio-utils
      - playerctl
      - brightnessctl
      - wob
      - fuzzel
      - wofi
      - bemenu
      - rofi-wayland
      - rofimoji
      - lm_sensors
      - gammastep-indicator

      # cli
      - aria2
      - aspell
      - bat
      - bandwhich
      - bottom
      - ctop
      - curl
      - gh
      - git-delta
      - exa
      - fd-find
      - direnv
      - fzf
      - fzy
      - git
      - git-lfs
      # - glow
      - gnupg
      - gnuplot
      - htop
      - httpie
      - hub
      - hyperfine
      - jq
      # - languagetool
      - lazydocker
      - lazygit
      - neovim
      - nnn
      - nodejs
      - ncdu
      - osmium-tool
      - pass
      - procs
      - qemu
      - ranger
      - ripgrep
      - ShellCheck
      - shfmt
      - tealdeer
      - tmux
      # - tmuxinator
      - tokei
      - weechat
      - wget
      - wezterm
      - zoxide

- name: install brew tools
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    name:
      # cli
      - as-tree
      - broot
      - duf
      - dust
      - grc
      - markdownlint-cli
      - mdcat
      - pfetch
      - selene
      - stylua
      - starship
# - import_tasks: repos.yml

- name: install tools
  become: true
  dnf:
    name:
      # LinuxBrew Dependencies
      - "@Development Tools"
      - "@Multimedia"
      - procps-ng
      - curl
      - file
      - libxcrypt-compat

      # gui
      - alacritty
      - brave-browser-beta
      - dconf-editor
      - discord
      # - element
      - gnome-tweaks
      - kitty
      - foot
      - waybar
      - sway
      - wdisplays
      - nwg-launchers
      - nwg-panel
      - slurp
      - grim
      - wev
      - swaylock-effects
      - imv
      - blueman

      # Wayland Development
      - wayland-devel
      - libxkbcommon-devel

      # Gaming
      - lutris
      - steam
      - wine
      - mangohud

      # utils
      - clipman
      - pulseaudio-utils
      - playerctl
      - brightnessctl
      - wob
      - fuzzel
      - wofi
      - bemenu
      - rofi-wayland
      - rofimoji
      - lm_sensors
      - gammastep-indicator

      # cli
      - aria2
      - aspell
      - bat
      - bandwhich
      - bottom
      - ctop
      - curl
      - gh
      - git-delta
      - exa
      - fd-find
      - direnv
      - fzf
      - fzy
      - git
      - git-lfs
      # - glow
      - gnupg
      - gnuplot
      - htop
      - httpie
      - hub
      - hyperfine
      - jq
      # - languagetool
      - lazydocker
      - lazygit
      - neovim
      - nnn
      - nodejs
      - ncdu
      - osmium-tool
      - pass
      - procs
      - qemu
      - ranger
      - ripgrep
      - ShellCheck
      - shfmt
      - tealdeer
      - tmux
      # - tmuxinator
      - tokei
      - weechat
      - wget
      - wezterm
      - zoxide

- name: install brew tools
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    name:
      # cli
      - as-tree
      - broot
      - duf
      - dust
      - grc
      - markdownlint-cli
      - mdcat
      - pfetch
      - selene
      - stylua
      - starship
- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)
- include: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include: core-apps.yml

# Install and configure zsh
- include: zsh.yml
  when: setup_zsh == True

# Web Browser
- include: "{{browser}}.yml"

# Terminal web browsers
- include: terminal_browsers.yml
  when: install_terminal_browsers == True

# Office
- include: office.yml
  when: install_office == True

# AUR apps
- include: aur.yml
  when: use_aur == True
