- name: install tools
  become: true
  pacman:
    update_cache: yes
    name:
      # cli
      - bat
      - curl
      - git-delta
      - exa
      - direnv
      - fzf
      - fzy
      - git
      - git-lfs
      - gnupg
      - gnuplot
      - htop
      - httpie
      - jq
      - neovim
      - nodejs
      - ripgrep
      - tmux
      - wget
      - wezterm
      - zoxide

