# - import_tasks: repos.yml

- name: install tools
  become: true
  dnf:
    name:
      # cli
      - aria2
      - aspell
      - bat
      - bandwhich
      - bottom
      - ctop
      - curl
      - gh
      - git-delta
      - exa
      - fd-find
      - direnv
      - fzf
      - fzy
      - git
      - git-lfs
      - gnupg
      - gnuplot
      - htop
      - httpie
      - hub
      - hyperfine
      - jq
      - lazydocker
      - lazygit
      - neovim
      - nnn
      - nodejs
      - ncdu
      - osmium-tool
      - pass
      - procs
      - qemu
      - ranger
      - ripgrep
      - shfmt
      - tmux
      - wget
      - wezterm
      - zoxide

