- name: install tools
  become: true
  package:
    update_cache: yes
    name:
      - bat
      - curl
      - exa
      - fzf
      - fzy
      - git
      - git-delta
      - htop
      - httpie
      - kitty
      - lazygit
      - less
      - neovim
      - nodejs
      - ripgrep
      - tmux
      - wezterm
      - wget
      - zoxide

