# - import_tasks: repos.yml

- name: install tools
  become: true
  dnf:
    name:
      # LinuxBrew Dependencies
      - "@Development Tools"
      - "@Multimedia"
      - procps-ng
      - curl
      - file
      - libxcrypt-compat

      # gui
      - dconf-editor
      - foot
      - waybar
      - wdisplays
      - nwg-launchers
      - nwg-panel
      - slurp
      - grim
      - wev
      - imv
      - blueman

      # Wayland Development
      - wayland-devel
      - libxkbcommon-devel

      # utils
      - clipman
      - pulseaudio-utils
      - playerctl
      - brightnessctl
      - wob
      - fuzzel
      - wofi
      - bemenu
      - rofi-wayland
      - rofimoji
      - lm_sensors
      - gammastep-indicator

      # cli
      - aria2
      - aspell
      - bat
      - bandwhich
      - bottom
      - ctop
      - curl
      - gh
      - git-delta
      - exa
      - fd-find
      - direnv
      - fzf
      - fzy
      - git
      - git-lfs
      # - glow
      - gnupg
      - gnuplot
      - htop
      - httpie
      - hub
      - hyperfine
      - jq
      # - languagetool
      - lazydocker
      - lazygit
      - neovim
      - nnn
      - nodejs
      - ncdu
      - osmium-tool
      - pass
      - procs
      - qemu
      - ranger
      - ripgrep
      - ShellCheck
      - shfmt
      - tealdeer
      - tmux
      # - tmuxinator
      - tokei
      - weechat
      - wget
      - wezterm
      - zoxide

