- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)
- include: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include: core-apps.yml

# Install and configure zsh
- include: zsh.yml
  when: setup_zsh == True

# Web Browser
- include: "{{browser}}.yml"

# Terminal web browsers
- include: terminal_browsers.yml
  when: install_terminal_browsers == True

# Office
- include: office.yml
  when: install_office == True

# AUR apps
- include: aur.yml
  when: use_aur == True
