- name: copr
  become: yes
  community.general.copr:
    name: "{{item}}"
  loop:
    - agriffis/neovim-nightly
    - alebastr/sway-extras
    - atim/bandwhich
    - atim/bottom
    - atim/lazydocker
    - atim/lazygit
    - fuhrmann/ctop
    - lehrenfried/fzy
    - eddsalkield/swaylock-effects