### Playbook Configuration Variables

## User info
username: jp

## Task Configuration
setup_zsh: True

## App Preferences
## ===========================
# Web Browser
# Value can be: vivaldi, firefox, brave, or chromium
browser: chromium

## When set to True, will install elinks and w3m
install_terminal_browsers: True

## Installs LibreOffice Fresh when True
install_office: True

## AUR vars
## ===========================
use_aur: True

aur:
    dir: aur
    packages:
        - yay
        - downgrade
        - zplug
        - miller
        - myrepos
        - ctmg
        - spiped
## ===========================